### ISSUE TITLE
help a noob out?

### ISSUE THREAD

**Issue by simon7904** [Hakanaou/deepLuna#12]
Got the the "translate" part, but nothing happens and says  TypeError: 'type' object is not subscriptable in the python IDE

**Comment by Hakanaou** [comment]
Are you using the latest version of deepLuna? If no, try with the latest (not from the release, click on Code/Download as a ZIP, always prefer this method to get the latest iteration).
If this doesn't help, I will need:
- More information on the error appearing in the Python IDE (a screenshot/copy paste of all there is, there are information about the precise lines in the code where it fails, and without them I cannot do much)
- The precise lines that you were trying to translate.

**Comment by alejandromonux** [comment]
Hello. I'm a different person from the one who opened the issue, but I've encountered the same error when using the "insert" function.

The error code is as follows: (Full directory hidden for privacy)

_Traceback (most recent call last):
  File "Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "deepLuna.py", line 1518, in function_insert_translation
    self.enregistrer_fichier()
  File "deepLuna.py", line 1718, in enregistrer_fichier
    self.table_file = self.reinsert_daytable(self.table_scr_file,self.table_file)
  File "deepLuna.py", line 1510, in reinsert_daytable
    if self.splitDayTable[self.i][0] == self.newMainTable[self.j][0] and self.splitDayTable[self.i][2] != 'TRANSLATION':
TypeError: 'type' object is not subscriptable_


I've also observed that in this situation _splitDayTable_ is empty from the loop in lines 1505 and 1506. 

The lines I'm trying to translate are all that's available up to date in Tsukihimate's _current_en_script_. I'm attaching the table.txt and table_scr.txt files (I assume it's what the script uses as a database). 
[table_scr.txt](https://github.com/Hakanaou/deepLuna/files/7270440/table_scr.txt)
[table.txt](https://github.com/Hakanaou/deepLuna/files/7270441/table.txt)

Hope this works clarify the error,
Thank you.

**Comment by Hakanaou** [comment]
I think you're using an older version of deepLuna, in the most recent version this bug should've been corrected - I managed to successfully reinsert your files in the script_text.mrg file. Please download the version from main (i.e. click on Code/Download as zip or fetch and pull the deepLuna repo - don't use the release files, they're already a bit outdated), and tell me if it's working.

**Comment by alejandromonux** [comment]
Hello, thank you for the quick answer.

I updated the game to 1.0.2 and downloaded the main branch of deepLuna and tried again. I get the same error as before. I'm using the IDE PyCharm and the rom was dumped using Yuzu. Since the files work on your end, I assume it was dumped correctly.

**Comment by Hakanaou** [comment]
When you put the allscr.mrg and script_text.mrg in deepLuna folder, are both of them from 1.0.2? Because the allscr.mrg is the file that changes the structure of lines. If it's the already the case, then I'll have to think a bit and see how to debug this.

**Comment by alejandromonux** [comment]
Yes, I dumped the rom again after updating and used this new files for the deepLuna folder.

**Comment by alejandromonux** [comment]
I just tried with that python version and the last deepLuna version and I got it to work. Thank you!
