### ISSUE TITLE
Issue with inserting translation

### ISSUE THREAD

**Issue by shingle-bells** [Hakanaou/deepLuna#15]
When I press the insert button on the translation window, I get this error in the console window:
```
Saving file, please wait...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\fergu\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\fergu\AppData\Roaming\yuzu\load\01001DC01486A000\deepLuna\romFS\deepLuna.py", line 1518, in function_insert_translation
    self.enregistrer_fichier()
  File "C:\Users\fergu\AppData\Roaming\yuzu\load\01001DC01486A000\deepLuna\romFS\deepLuna.py", line 1718, in enregistrer_fichier
    self.table_file = self.reinsert_daytable(self.table_scr_file,self.table_file)
  File "C:\Users\fergu\AppData\Roaming\yuzu\load\01001DC01486A000\deepLuna\romFS\deepLuna.py", line 1510, in reinsert_daytable
    if self.splitDayTable[self.i][0] == self.newMainTable[self.j][0] and self.splitDayTable[self.i][2] != 'TRANSLATION':
TypeError: 'type' object is not subscriptable
```
Any ideas as to what I can do to fix the issue? I'm currently using python 3.8.5.

**Comment by shingle-bells** [comment]
Update: Updating my Python version to 3.9.7 seems to have fixed the issue. I managed to insert the script file properly.
