### ISSUE TITLE
Assertion Error on Insert

### ISSUE THREAD

**Issue by karrylarry23** [Hakanaou/deepLuna#39]
I imported the translated script from the Tsukihimates github into deepLuna. That worked, but whenever I click insert I get this error:

**AssertionError: Unhandled control code 'justify_right' in line '%{justify_right}A dissolving dog.'**

I dig some digging and this line's from Arc route day 2. I'm also using the main branch of deepLuna, not any releases, so that shouldn't be an issue.

Am I using the wrong version of the translated script or something by any chance? 

Full Traceback just in case:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/mnt/c/Users/prasa/deepLuna/luna/ui/translation_window.py", line 403, in insert_translation
    mzp_data = self._translation_db.generate_script_text_mrg(
  File "/mnt/c/Users/prasa/deepLuna/luna/translation_db.py", line 184, in generate_script_text_mrg
    offset_to_string = self.generate_linebroken_text_map(perform_charswap)
  File "/mnt/c/Users/prasa/deepLuna/luna/translation_db.py", line 243, in generate_linebroken_text_map
    coded_text = RubyUtils.apply_control_codes(tl_text)
  File "/mnt/c/Users/prasa/deepLuna/luna/ruby_utils.py", line 222, in apply_control_codes
    assert False, \
AssertionError: Unhandled control code 'justify_right' in line '%{justify_right}A dissolving dog.'

**Comment by rschlaikjer** [comment]
The script is not finished. We would ask that you wait for the final release if you wish to read the game. Thank you for your patience.
