### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by Flawox** [Hakanaou/deepLuna#43]
Sorry, I don't know anything about python :(
When running deepLuna.py through IDDLE Shell, errors appear
Also opens a blank window with the name Welcome to deepLuna

Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=========== RESTART: C:\Users\User\Desktop\deepLuna-main\deepLuna.py ===========
Traceback (most recent call last):
  File "C:\Users\User\Desktop\deepLuna-main\deepLuna.py", line 8, in <module>
    main()
  File "C:\Users\User\Desktop\deepLuna-main\deepLuna.py", line 5, in main
    StartWindow().mainloop()
  File "C:\Users\User\Desktop\deepLuna-main\luna\ui\start_window.py", line 30, in __init__
    icon = Image.open("icone.png").resize((140, 140))
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'icone.png'

**Comment by rschlaikjer** [comment]
This is now fixed, but I'd recommend using the command line tools and raw script format over the UI, since they're what we actually used internally / are more fleshed out than the UI at this point.
